qualtrics_link/urls.py
from django.urls import path, re_path

from qualtrics_link import views

app_name = 'ql'
urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    path('internal', views.internal, name='internal'),
    re_path(r'^launch$', views.launch, name='launch'),
    re_path(r'^monitor$', views.MonitorResponseView.as_view()),
    re_path(r'^user_accept_terms$', views.user_accept_terms, name='user_accept_terms'),
    re_path(r'^user_decline_terms$', views.user_decline_terms, name='user_decline_terms'),
]

qualtrics_link/models.py
from django.db import models


class SchoolCodeMapping(models.Model):
    """
    Note: This is a copy of the School_code_mapping DB Table from RPT database.
    IDDB has a different set of school codes for students and a completely
    different set for employees. This mapping table reconciles both of those
    into a single table. It is a bit complex  to append the school data to the
    ldap_people_plus view and since this rarely changes, we are fetching and
    maintaining a copy locally

    TODO: Revisit and fix this when we move to new people service
    """

    student_school_code = models.CharField(max_length=2)
    student_school_desc = models.CharField(max_length=64)
    employee_school_code = models.CharField(max_length=10)


    class Meta:
        db_table = 'school_code_mapping'

    def __unicode__(self):
        return self.student_school_code

class Acceptance(models.Model):
    """
    This is a table used to track and store Qulatrics user acceptance of terms
    of service
    """
    user_id = models.CharField(max_length=200, primary_key=True)
    acceptance_date = models.DateTimeField()
    ip_address = models.CharField(max_length=100)

    class Meta:
        db_table = 'acceptance'

    def __unicode__(self):
        return self.id


class QualtricsUser(models.Model):
    univ_id = models.CharField(max_length=32)
    qualtrics_id = models.CharField(max_length=32)
    manually_updated = models.BooleanField()

    class Meta:
        db_table = 'qualtrics_user'

qualtrics_link/forms.py
from django import forms
from qualtrics_link import util


class SpoofForm(forms.Form):
    huid = forms.CharField(max_length=15, required=False)


class QualtricsUserAdminForm(forms.Form):
    division = forms.ChoiceField(choices=util.DIVISION_CHOICES)
    role = forms.ChoiceField(choices=util.ROLE_CHOICES)
    manually_updated = forms.ChoiceField(choices=(('True', 'True'), ('False', 'False')))

qualtrics_link/views.py
import datetime
import logging
import time
import urllib.request, urllib.parse, urllib.error
from datetime import date
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.utils import timezone
from django.views.decorators.http import require_http_methods
from harvardkey_cas.decorators import group_membership_restriction
from icommons_common.monitor.views import BaseMonitorResponseView

import qualtrics_link.util as util
from qualtrics_link.forms import SpoofForm, QualtricsUserAdminForm
from qualtrics_link.models import Acceptance, QualtricsUser

logger = logging.getLogger(__name__)


class MonitorResponseView(BaseMonitorResponseView):
    def healthy(self):
        return True

# BLOCK_SIZE=16
BS = 16
pad = lambda s: s + (BS - len(s) % BS) * chr(BS - len(s) % BS)
unpad = lambda s: s[0:-ord(s[-1])]


@require_http_methods(['GET'])
def index(request):
    return render(request, 'qualtrics_link/index.html')


@login_required
@require_http_methods(['GET'])
def launch(request):
    user_can_access = False
    client_ip = util.get_client_ip(request)

    # Get the expiration date in the correct format i.e. '2008-07-16T15:42:51' (date format is same as above)
    # In this case we take the current time and add 1 minutes (60 seconds)
    current_time = time.time()
    current_date = datetime.datetime.utcfromtimestamp(current_time).strftime('%Y-%m-%dT%H:%M:%S')

    # Get the expiration date in the correct format i.e. '2008-07-16T15:42:51' (date format is same as above)
    # In this case we take the current time and add 5 minutes (300 seconds)
    expiration_date = datetime.datetime.utcfromtimestamp(current_time + 300).strftime('%Y-%m-%dT%H:%M:%S')

    huid = request.user.username
    user_in_whitelist = util.is_user_in_whitelist(huid)

    # make sure this is an HUID
    if not huid.isdigit() and not user_in_whitelist:
        logger.info("xidnotauthorized\t{}\t{}".format(current_date, client_ip))
        return render(request, 'qualtrics_link/notauthorized.html', {'request': request})

    # The PersonDetails object extends the Person model with additional attributes
    person_details = util.get_person_details(huid)

    if person_details is None:
        logger.error('No records with the huid of {} could be found'.format(huid))
        return render(request, 'qualtrics_link/error.html', {'request': request})

    # Use time.now() for the correct formatting to match the DateTimeField in the DB
    # This is a different formatting than the above current_date var
    today = timezone.now()

    # Check if the user can use qualtrics or not
    # the value of user_can_access is set to False by default
    # If the user is in the whitelist, they have access
    # Otherwise the user must have at least a valid department or school as well as
    # have a role end date that is either None or today or greater.
    if user_in_whitelist:
        user_can_access = True
    elif (person_details.valid_dept or person_details.valid_school) and \
         (person_details.role_end_date is None or person_details.role_end_date >= today):
        user_can_access = True

    if user_can_access:
        # Check to see if the user has accepted the terms of service

        user_acceptance = None
        try:
            user_acceptance = Acceptance.objects.get(user_id=huid)
        except Acceptance.DoesNotExist:
            logger.info('User %s has not  accepted term of service ', huid)
        except:
            logger.error('Exception in checking for user acceptance, '
                         'user_id:%s', huid)
            return render(request, 'qualtrics_link/error.html')

        #  Render agreement page if user has not accepted term of service
        if not user_acceptance:
            return render(request, 'qualtrics_link/agreement.html',
                          {'request': request})

        enc_id = util.get_encrypted_huid(huid)
        key_value_pairs = "id={}&timestamp={}&expiration={}&firstname={}&lastname={}&email={}&UserType={}&Division={}"
        key_value_pairs = key_value_pairs.format(enc_id,
                                                 current_date,
                                                 expiration_date,
                                                 person_details.first_name,
                                                 person_details.last_name,
                                                 person_details.email,
                                                 person_details.role,
                                                 util.DIVISION_MAPPING[person_details.division])
        qualtrics_link = util.get_qualtrics_url(key_value_pairs)
        logger.info("{}\t{}\t{}\t{}".format(current_date, client_ip, person_details.role, person_details.division))

        # Update the users Qualtrics role and division to the most current information prior to redirecting
        try:
            qu = QualtricsUser.objects.filter(univ_id=person_details.id).first()
            if qu and qu.manually_updated is False:
                util.update_qualtrics_user(user_id=qu.qualtrics_id,
                                           division=util.DIVISION_MAPPING[person_details.division],
                                           role=util.USER_TYPE_MAPPING[person_details.role])
        except Exception as ex:
            logger.info("Exception while retrieving QualtricsUser and/or performing update of their information. "
                        "Qualtrics user id: {}, University ID: {}".format(qu.qualtrics_id, qu.univ_id), ex)

        # The redirect line below will be how the application works if everything is good for the user.
        return redirect(qualtrics_link)

    else:
        logger.info("notauthorized\t{}\t{}\t{}\t{}".format(current_date, client_ip,
                                                           person_details.role, person_details.division))
        return render(request, 'qualtrics_link/notauthorized.html', {'request': request})


@login_required
@group_membership_restriction(settings.QUALTRICS_LINK.get('QUALTRICS_AUTH_GROUP'))
@require_http_methods(['GET', 'POST'])
def internal(request):

    user_can_access = False
    client_ip = util.get_client_ip(request)

    # get the current date in the correct format i.e. '2008-07-16T15:42:51'
    current_time = time.time()
    current_date = datetime.datetime.utcfromtimestamp(current_time).strftime('%Y-%m-%dT%H:%M:%S')

    # get the expiration date in the correct format i.e. '2008-07-16T15:42:51' (date format is same as above)
    # In this case we take the current time and add 10 minutes (600 seconds)
    expiration_date = datetime.datetime.utcfromtimestamp(current_time + 600).strftime('%Y-%m-%dT%H:%M:%S')

    # Initialize the 2 forms
    qualtrics_user_update_form = QualtricsUserAdminForm()
    spoof_form = SpoofForm()

    # Set the initial huid to the person using the internal page
    huid = request.user.username
    huid = huid.strip()
    if request.method == 'POST':
        huid = request.POST['huid']
        logger.info('USER: ' + str(request.user.username) + ' Spoofing: ' + huid)

        # If the Qualtrics admin form was submitted, validate and then send division and role data
        if 'role' in request.POST:
            qualtrics_user_update_form = QualtricsUserAdminForm(data=request.POST)

            if qualtrics_user_update_form.is_valid():
                # There is currently some HUID's that have multiple Qualtrics accounts.
                q_user_qset = QualtricsUser.objects.filter(univ_id=huid)
                if len(q_user_qset) > 0:
                    q_user = q_user_qset[0]
                    qualtrics_id = q_user.qualtrics_id
                    division = util.DIVISION_MAPPING[request.POST['division']]
                    role = util.USER_TYPE_MAPPING[request.POST['role']]
                    # Perform the update to Qualtrics with the obtained values
                    util.update_qualtrics_user(qualtrics_id, division, role)
                    # Save the users manually_updated field
                    q_user.manually_updated = request.POST['manually_updated']
                    q_user.save()

    if 'spoofid' in request.session:
        # We got here because the user accepted the tos and we needed a way to stay the spoofed user
        huid = request.session.get('spoofid')
        huid = huid.strip()
        logger.info('USER: ' + str(request.user.username) + ' Spoofing: ' + str(request.session.get('spoofid', 'None')))
        spoof_form = SpoofForm({'huid': huid.strip()})

    user_in_whitelist = util.is_user_in_whitelist(huid)

    if not huid.isdigit() and not user_in_whitelist:
        logger.info("xidnotauthorized\t{}\t{}".format(current_date, client_ip))
        return render(request, 'qualtrics_link/notauthorized.html', {'request': request})

    # The PersonDetails object extends the Person model with additional attributes
    person_details = util.get_person_details(huid)

    if person_details is None:
        logger.error('No records with the huid of {} could be found'.format(huid))
        return render(request, 'qualtrics_link/error.html', {'request': request})

    # Check if the user can use qualtrics or not
    # the value of user_can_access is set to False by default
    # if any of the checks here pass we set user_can_access to True
    if person_details.valid_dept or person_details.valid_school or user_in_whitelist:
        user_can_access = True

    if user_can_access:

        # Set the initial values of the Qualtrics Admin form
        qualtrics_user_update_form.initial['division'] = person_details.division
        qualtrics_user_update_form.initial['role'] = person_details.role
        qualtrics_user_update_form.initial['manually_updated'] = False

        qualtrics_user_in_db = False
        try:

qualtrics_link/templates/qualtrics_link/_unauthorized_message.html
<h3>
  We're sorry, your ID doesn't appear to have access to this Qualtrics license.
</h3>
<p>
  <ul>
    <li>
      HMS/HSDM affiliates--<a href="https://collaborate.hms.harvard.edu/x/z4Gm">instructions
      on how to login to your HMS Qualtrics account:
      https://collaborate.hms.harvard.edu/x/z4Gm</a>
    </li>
    <li>
      HBS affiliates--<a href="https://hbs.qualtrics.com/ControlPanel/">login
      to your HBS Qualtrics account: https://hbs.qualtrics.com/ControlPanel/</a>
      or to create an account contact
      <a href="mailto:ithelp@hbs.edu">ithelp@hbs.edu</a> (617) 495-6600.
    </li>
    <li>
      XID holders are not able to access Qualtrics through this license.
    </li>
  </ul>
</p>

<p>
  If you think that you should be able to access Qualtrics through this license,
  please <a href="mailto:ithelp@harvard.edu">contact us at ithelp@harvard.edu</a>
  and ask us to verify that your account is set up correctly.
</p>

qualtrics_link/templates/qualtrics_link/agreement.html
{% extends "qualtrics_link/base.html" %}

{% block title %}Qualtrics Terms of Service Agreement{% endblock %}
{% block pagetitle %}Qualtrics Terms of Service Agreement{% endblock %}

{% block content %}
	<h2>Qualtrics Agreement</h2>


    <p>The Qualtrics survey tool is available for use by Harvard faculty, staff, and students in support of the university's educational mission and organizational goals.  By using Qualtrics you are agreeing to adhere to the following terms:
    </p>
    <label for="agree1">Appropriate Use</label>
    <ul id="agree1">

    <li>No High Risk Confidential Information
    University policies prohibit the use of Qualtirics for "high-risk, confidential information," or HRCI. For a definition of HRCI, please see http://www.security.harvard.edu/glossary-terms.  For Harvard security policies, please see, http://ww.security.harvard.edu. For research data security policies, please see: http://security.harvard.edu/focus-research.
    </li>
    <li>Human Subject Research Must Be Approved by an IRB
    In accordance with federal regulations and Harvard University policies, all research involving human subjects must be reviewed and approved by an Institutional Review Board (IRB) prior to any research intervention with a participant. Please visit the Web site for the Harvard Office of the Vice Provost for Research for more information: http://vpr.harvard.edu/. You are responsible for ensuring compliance with federal regulations and Harvard research policies.
    </li>
    <li>Protecting Privacy
    All surveys must protect the privacy and confidentiality of student, employee and other institutional information, as required by FERPA (privacy of student information), appropriate state laws, and Harvard policies.  Although a closed group of participants may complete Qualtrics surveys without the individuals explicitly having to identify themselves, the Qualitrics software stores identifying information in its databases. Consequently, Qualtrics can not be used with absolute guarantees of anonymity for your participants.
    </li>
    <li>Compliance with all other  Laws ad Policies
    Surveys must comply with all other applicable University policies and state and federal laws, including the federal [http://www.copyright.gov/help/faq]   [http://www.copyright.gov/help/faq] laws  for copyright [http://www.copyright.gov/help/faq]   [http://www.copyright.gov/help/faq]  and privacy.
    </li>
    <li>The survey service may not be used for personal or commercial gain</li>
    <li>Unsolicited mass communication may not be delivered in conjunction with the survey service</li>
    <li>Survey participants should be informed that their survey data will be stored on a third party server and that, while the third party has agreed to keep the data confidential, Harvard does not control the security of that server.
    </li>
    </ul>
    <p>
    The Office of the University CIO reserves the right to change, at any time, and at its sole discretion, this survey service and these Terms of Use. Notification of changes will be published at http://survey.harvard.edu.
    </p>
    <p>
    I understand that The Harvard Qualtrics survey tool may not be used to store or process high-risk, confidential information (HRCI) as defined by Harvard policy and federal law. I understand that all uses of the Harvard Qualtrics tool for human subjects research must be approved by my IRB, and that I should consult with the Office of the Vice Provost for Research for more information.
    </p>
    <label for="disclaimer">Disclaimer</label>
    <p id="disclaimer">
    The surveys created or the responses supplied using the survey service do not in any way constitute official Harvard content. The views and opinions expressed are strictly those of the survey&rsquo;s authors. The contents of the surveys and responses have not been reviewed or approved by Harvard.
    </p>


<a href="{% url 'ql:user_accept_terms' %}" class="btn btn-primary">Accept</a>

<a href="{% url 'ql:user_decline_terms' %}" class="btn btn-link"> Decline </a>
 
{% endblock %}

{% block javascript %}
{{ block.super }}

<script>

</script>

{% endblock %}

qualtrics_link/templates/qualtrics_link/error.html
{% extends "qualtrics_link/base.html" %}

{% block title %}Qualtrics Terms of Service Agreement{% endblock %}
{% block pagetitle %}Qualtrics Terms of Service Agreement{% endblock %}

{% block content %}

<p>
An error has occurred, please try again or contact <a href="mailto:ithelp@harvard.edu">ithelp@harvard.edu</a> if the problem persists.
</p>

<p>
	<a href="https://harvard.service-now.com/ithelp?id=kb_article&sys_id=048d71dddb3c0340a752f1a51d9619a9" class="btn btn-primary">What is Qualtrics and how do I access it?</a>
</p>

{% endblock %}

{% block javascript %}
{{ block.super }}
{% endblock %}

qualtrics_link/templates/qualtrics_link/index.html
{% extends "qualtrics_link/base.html" %}

{% block title %}Qualtrics Terms of Service Agreement{% endblock %}
{% block pagetitle %}Qualtrics Terms of Service Agreement{% endblock %}

{% block stylesheet %}
{{ block.super }}
{% endblock %}

{% block content %}

<h2>Qualtrics@Harvard</h2>

<p>Qualtrics is web-based survey software available for use by
Harvard faculty, students and staff to support teaching and
research at Harvard. Surveys can be created and distributed by
anyone with a Harvard PIN login. Ideal for:</p>

<ul>
<li>Simple one-time surveys to ongoing research</li>
<li>Targeting respondents by e-mail address</li>
<li>Publicly available surveys</li>
<li>A wide range of question types</li>
<li>Branching and piping</li>
<li>Robust reporting</li>
</ul>


{% endblock %}

{% block javascript %}
{{ block.super }}
{% endblock %}

qualtrics_link/templates/qualtrics_link/main.html
{% extends "qualtrics_link/base.html" %}

{% block title %}Qualtrics Status{% endblock %}
{% block pagetitle %}Qualtrics Status{% endblock %}

{% block stylesheet %}
{{ block.super }}

<style>
	.my-new-list {
		display: normal;
		float: right;
	}

	caption {
		margin-bottom: 10px;
		font-size: large;
		font-weight: bold;
	}
	.caption {
		margin-bottom: 10px;
		font-size: large;
		font-weight: bold;
	}
	td {
		display: table-cell;
		word-break:break-word;
	}
	.title {
		text-align: center;
	}
	.spoof-form {
		width: 38%;
	}

	.qualtrics_admin {
		padding-bottom: 50px;
	}

</style>

{% endblock %}

{% block content %}

<h1>Qualtrics Internal Dashboard</h1>

<br />

<div class="well spoof-form">
<h4>Enter an HUID to spoof</h4>
<form action="internal" method="POST" role="form">{% csrf_token %}
	{% for field in spoof_form %}
	{{ field.label_tag }}&nbsp;{{ field }}
	{% endfor %}
	<input type="submit" value="Submit" class="btn btn-default"/>
</form>
</div>


<br />

<table>
	<tr>
		<td valign="top">
			<table class="table table-striped table-hover">
			 	<caption>People Data</caption>
				<tr> <th>First name</th><td>{{person.name_first}}</td></tr>
				<tr> <th>Last name</th><td>{{person.name_last}}</td></tr>
				<tr> <th>Email</th><td>{{person.email_address}}</td></tr>
				<tr> <th>Role</th><td>{{person.role_type_cd}}</td></tr>
				<tr> <th>Department</th><td>{{person.faculty_cd}}</td></tr>
				<tr> <th>School affiliations</th><td>{{processed_data.school_affiliations}}</td></tr>
				<tr> <th>ID</th><td>{{person.univ_id}}</td></tr>
			</table>
			<p><a href="{{ssotestlink}}" class="btn btn-primary">Qualtrics SSO test Link</a></p>
			<p><a href="{{qualtricslink}}" class="btn btn-primary">Qualtrics Survey Link</a></p>
		</td>
		<td valign="top">
			 <table class="table table-striped table-hover">
			 	<caption>Processed Data</caption>
			   	<tr> <th>user_id</th><td>{{huid}} </td></tr>
			    <tr> <th>authenticated</th><td>{{request.user.is_authenticated}}</td></tr>
				<tr> <th>First name</th><td>{{processed_data.first_name}}</td></tr>
				<tr> <th>Last name</th><td>{{processed_data.last_name}}</td></tr>
				<tr> <th>Email</th><td>{{processed_data.email}}</td></tr>
				<tr> <th>Role</th><td>{{processed_data.role}}</td></tr>
				<tr> <th>Division</th><td>{{processed_data.division}}</td></tr>
				<tr> <th>ID</th><td>{{processed_data.id}}</td></tr>
				<tr> <th>Valid School</th><td>{{processed_data.valid_school}}</td></tr>
				<tr> <th>Valid Dept</th><td>{{processed_data.valid_dept}}</td></tr>
			    <tr><th>user_in_whitelist</th><td>{{user_in_whitelist}}</td></tr>
			</table>
		</td>
		<td valign="top" id="data">
		</td>
	</tr>
</table>

<div class="well qualtrics_admin">
	<h4>Manage Qualtrics Division and/or Role</h4>
	{% if not qualtrics_user_in_db %}
		<div class="alert alert-warning" role="alert">
			This user is not currently in our Postgres table. Please contact a dev for further assistance.
		</div>
	{% endif %}
	<form action="internal" method="POST">{% csrf_token %}
		<div class="col-sm-4">
			Division: {{ qualtrics_user_update_form.division }}
		</div>
		<div class="col-sm-3">
			Role: {{ qualtrics_user_update_form.role }}
		</div>
		<div class="col-sm-4">
			Skip in update job: {{ qualtrics_user_update_form.manually_updated }}
		</div>
		<input type="hidden" name="huid" value='{{ huid }}'>
		<div class="col-sm-1">
			{% if qualtrics_user_in_db %}
				<input type="submit" value="Submit" class="btn btn-primary">
			{% endif %}

		</div>
	</form>
</div>


{% endblock %}

qualtrics_link/templates/qualtrics_link/notauthinternal.html
{% extends "qualtrics_link/base.html" %}

{% block title %}Not Authorized{% endblock %}
{% block pagetitle %}Not Authorized{% endblock %}

{% block stylesheet %}
{{ block.super }}
<style type="text/css">
	.bold { font-weight: bold;}
	caption {
		margin-bottom: 10px;
		font-size: large;
		font-weight: bold;
	}
</style>
{% endblock %}

{% block content %}

{% include "qualtrics_link/_unauthorized_message.html" %}

<br />
<table>
	<tr>
		<td valign="top">
			<table class="table table-striped table-hover">
			 	<caption>People Data</caption>
				<tr> <th>First name</th><td>{{person.name_first}}</td></tr>
				<tr> <th>Last name</th><td>{{person.name_last}}</td></tr>
				<tr> <th>Email</th><td>{{person.email_address}}</td></tr>
				<tr> <th>Role</th><td>{{person.role_type_cd}}</td></tr>
				<tr> <th>Department</th><td>{{person.faculty_cd}}</td></tr>
				<tr> <th>School affiliations</th><td>{{processed_data.school_affiliations}}</td></tr>
				<tr> <th>ID</th><td>{{person.univ_id}}</td></tr>
			</table>
		</td>
		<td valign="top">
			 <table class="table table-striped table-hover">
			 	<caption>Processed Data</caption>
			   	<tr> <th>user_id</th><td>{{huid}} </td></tr>
			    <tr> <th>authenticated</th><td>{{request.user.is_authenticated}}</td></tr>
				<tr> <th>First name</th><td>{{processed_data.first_name}}</td></tr>
				<tr> <th>Last name</th><td>{{processed_data.last_name}}</td></tr>
				<tr> <th>Email</th><td>{{processed_data.email}}</td></tr>
				<tr> <th>Role</th><td>{{processed_data.role}}</td></tr>
				<tr> <th>Division</th><td>{{processed_data.division}}</td></tr>
				<tr> <th>ID</th><td>{{processed_data.id}}</td></tr>
				<tr> <th>Valid School</th><td>{{processed_data.valid_school}}</td></tr>
				<tr> <th>Valid Dept</th><td>{{processed_data.valid_dept}}</td></tr>
			    <tr><th>user_in_whitelist</th><td>{{user_in_whitelist}}</td></tr>
			</table>
		</td>
		<td valign="top" id="data">
		</td>
	</tr>
</table>
<a href="{% url 'ql:internal' %}" class="btn btn-primary">Return to Survey Tools page</a>

{% endblock %}

{% block javascript %}
{{ block.super }}
{% endblock %}

qualtrics_link/templates/qualtrics_link/notauthorized.html
{% extends "qualtrics_link/base.html" %}

{% block title %}Not Authorized{% endblock %}
{% block pagetitle %}Not Authorized{% endblock %}

{% block stylesheet %}
{{ block.super }}
<style type="text/css">
.bold { font-weight: bold;}
</style>
{% endblock %}

{% block content %}

{% include "qualtrics_link/_unauthorized_message.html" %}

<br />
<p>
	<a href="http://surveytools.harvard.edu/" class="btn btn-primary">Return to Survey Tools page</a>
</p>

{% endblock %}

{% block javascript %}
{{ block.super }}
{% endblock %}